### PR TITLE
Fixes positional arguments for all environments

### PR DESCRIPTION
**Pull request by nathanoehlman**
The launch function in start was causing all sorts of problems with the passing through of positional arguments - worked fine on Mac, failed horribly on Linux and Travis CI and caused all sorts of issues.

After trying various permutations trying to make the function work, it has now been relegated to the scrap heap...

### CODE REVIEW

**Comment by DamonOehlman** [comment]
Looks good Nathan, one question was that `+extension RANDR` opt for xvfb required to get tests passing and thus should we document it somewhere?

**Comment by nathanoehlman** [comment]
Yeah - that's unnecessary. That was my attempt to remove the `Xlib:  extension "RANDR" missing on display ":99.0".` warnings that kept appearing - they still appear, so it doesn't fix anything, and the warning doesn't cause any problems apart from just messing up the logs, so I think I'll remove that bit.

**Comment by DamonOehlman** [comment]
Ah, that makes sense - good idea, shame it didn't do something as I'm not a massive fan of that warning message either...

**Comment by DamonOehlman** [comment]
Published as `2.7.2`

**Comment by nathanoehlman** [comment]
Awesome - thanks :)

**Pull request merged**
