### PR TITLE
setup: ignore electron, nw and android

### PR DESCRIPTION
**Pull request by fippo**
adds the option to install electron via npm

### CODE REVIEW

**Comment by fippo** [comment]
Not sure if this behaviour makes sense. Maybe ignore it alltogether and make it the users problem?

I already do another npm install for the launcher in https://github.com/webrtc/adapter/pull/763 but that failed because setup.sh broke.

**Comment by fippo** [comment]
test failures due to #39

**Comment by fippo** [comment]
went a different way and decided to ignore stuff we don't support like android (as browser version), electron and nw

**Review by aullman — APPROVED** [review]

**Comment by aullman** [comment]
LGTM, we used "electron" with a lower case E and "edge" with a lower case E.

**Comment by fippo** [comment]
hrm... karma-electron-launcher uses Electron so i went for that. I wonder about a whitelist instead of a blacklist... :-)

**Comment by fippo** [comment]
published as 4.4.0

**Pull request merged**
