### PR TITLE
use browser-sleuth directly

### PR DESCRIPTION
**Pull request by fippo**
instead of relying on an instance running on a server

### CODE REVIEW

**Comment by fippo** [comment]
https://browser-version-api.herokuapp.com/linux/chrome/stable currently returns an error

@nathanoehlman PTAL - see also the 2018 (:older_man:) discussion in #34. This seems like a minimal change

**Comment by fippo** [comment]
ping -- happy new year!

**Comment by fippo** [comment]
oh look at #41! I am getting :older_man:

**Comment by fippo** [comment]
Lets do a major version bump and be done with it?

(i suspect we'll need to deal with [omahaproxy going away](https://groups.google.com/a/chromium.org/g/chromium-dev/c/uH-nFrOLWtE/m/uCGXyOYqEwAJ) soon too)

**Comment by DamonOehlman** [comment]
> Lets do a major version bump and be done with it?

Agreed.  You should have the ability to do this with your `npm` powers.  Let me know if you'd like me to do it though.

**Comment by fippo** [comment]
I have the power and found the time ;-)
Published as 5.0.0

**Comment by fippo** [comment]
Ah, missed the cut command (also years ago!)
Publishing with 4cce18d9515197da832e04622ce3b79f6d089810 as 5.0.1

**Pull request merged**
