### PR TITLE
Move browser binaries and symlinks out of the user's homedir.

### LINKED ISSUE #3: Make multirunner more useful for executing locally?
This is as much a query as a bug, to see if it's worthwhile making a pull request...
travis-multirunner executed locally has two irritating properties:
- it puts links into ~/bin
- it leaves downloaded tar.gz files in the home directory of the project.

I think it would be nicer if we had a subdir of the project directory called "travis-multirunner-workdir" where we could keep both the symlinks and the packages, and advise users that they could add this to their .gitignore file to avoid having it show up every time as "untracked file".

What do you think?

### PR DESCRIPTION
**Pull request by alvestrand**
This makes the test framework self-contained.

Fixes #3

### CODE REVIEW

**Comment by DamonOehlman** [comment]
Nice - Looking forward to merging this :)

I think you reference `browsers/` in some locations and `browser/` in others, which is why the tests are currently failing.

**Comment by alvestrand** [comment]
Yes, saw that. Fixing. Thank heavens for test suites :-)

**Comment by DamonOehlman** [comment]
Awesome - merging :)

**Comment by DamonOehlman** [comment]
Published `2.4.0`

**Pull request merged**
