### PR TITLE
setup: add lots of quotes everywhere

### PR DESCRIPTION
**Pull request by fippo**
in all places where there should be quotes

### CODE REVIEW

**Comment by fippo** [comment]
@aullman do you have an idea why this fails in safari unstable? I suspect its because the "unsafe" curl/sed combo no longer works but don't have a mac to verify

**Comment by fippo** [comment]
@aullman it seems we need to update the osx base image and there are now issues with soundflower?!

Shall I split the "add quotes" from those commits and merge despite STP failing?

**Comment by aullman** [comment]
Sorry for the late response.

Yes, there is an issue now where Safari tech preview requires Mac OS 10.12 now and you can’t install soundflower on it programmatically anymore. Which means you run into a bug where Safari crashes when you call getUserMedia because of this bug https://bugs.webkit.org/show_bug.cgi?id=172794

Not sure how long before that bug is fixed and I couldn’t find a way to install soundflower. There might be another way to get audio output on Travis? Not sure.

For now yeah, I would make STP and allowed failure and merge this in.

**Comment by fippo** [comment]
so setup.sh needs a small version bump but then soundflower crashes. Going to ignore the STP failure for this PR

**Comment by fippo** [comment]
works fine without quotes. Don't quote me ;-)

**Pull request closed without merging**
