### PR TITLE
Add Safari support

### PR DESCRIPTION
**Pull request by aullman**
Adds support for Safari. You can use Safari Technology Preview with `BROWSER=safari BVER=unstable` and stable with `BROWSER=safari BVER=stable`. Stable will just use the default version of Safari that is installed with Mac OS 10.12. Unstable will download Safari Technology Preview which now supports WebRTC. The `start-safari.sh` command turns on fake devices, allows insecure domains and allows devices access on localhost.

We should probably add the Safari download URL to the browsers.contralis.info service. Right now it's scraping from the Safari Tech Preview download site which is brittle.

### CODE REVIEW

**Comment by DamonOehlman** [comment]
@aullman woot, I was keeping an eye on this one :)

I'll merge the PR and bump the MAJOR version so it's very clearly an opt-in.  Have also added yourself, @fippo and @nathanoehlman as collaborators on this repo.

Adam - to that effect once I've created the new git tag for `4.0.0` would you be so kind as to draw up some simple release notes please?  Maybe highlighting the changes that you needed to make to the matrix settings in `travis.yml` to ensure the correct machine types were selected.

@nathanoehlman What needs to be done WRT browsers.contralis.info ??

**Comment by DamonOehlman** [comment]
@aullman PR in and `4.0.0` published.  Below is the link for creating new release notes ;)

https://github.com/DamonOehlman/travis-multirunner/releases/new?tag=v4.0.0

**Comment by fippo** [comment]
i would have slightly preferred "TechnologyPreview" as BVER but... yay, thanks Adam!

@youennf is there any recommended URL to download STP automatically?

**Comment by aullman** [comment]
Created :) Let me know if you think I should add any more details.

**Comment by aullman** [comment]
@fippo yeah, good point. I wasn't sure whether to stick with the existing "stable" "unstable" nomenclature. I was also thinking you could call STP "beta".

**Comment by fippo** [comment]
calling it TechnologyPreview avoids that nomenclature problem ;-)

**Comment by fippo** [comment]
https://github.com/webrtc/adapter/pull/593 failed because remote automation is not enabled. Does this need to write another setting and do a [sudo safaridriver as suggested here](https://webkit.org/blog/6900/webdriver-support-in-safari-10/)?

**Comment by fippo** [comment]
`defaults write com.apple.Safari IncludeDevelopMenu -bool true` 
should do the trick according to [stackoverflow](https://stackoverflow.com/questions/44006628/how-to-enable-allow-remote-automation-in-safari-progrmmatically)

oh wait. that person is asking that question ...

**Comment by fippo** [comment]
```
defaults write com.apple.safari ApplePersistenceIgnoreState YES
```
should this be tech preview as well?

I also just noticed the permissions plist trick. Neat!

**Comment by aullman** [comment]
@fippo yes, good catch, that should be SafariTechnologyPreview as well. I'm not sure what to do about the automation setting for WebDriver. I hadn't tested that yet and it [doesn't look like it's straight forward to turn on anymore](https://stackoverflow.com/questions/41629592/macos-sierra-how-to-enable-allow-remote-automation-using-command-line?answertab=oldest#tab-top). I'll look into it.

**Comment by aullman** [comment]
@youennf do you know how to turn on the "Allow Remote Automation" option programatically?

**Comment by fippo** [comment]
@burg might be able to help -- or listen to "we need this"

**Pull request merged**
